spring:
  application:
    name: hotel-pricing-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

aws:
  s3:
    bucket-name: hotel-etl-output-azooz59
    region: eu-north-1

logging:
  level:
    com.hotel.pricing: DEBUG